### ISSUE TITLE
Nuxt Web3 0.1.0 - setAbi and setContractAddress API

### ISSUE THREAD

**Issue by fncolon** [fncolon/nuxt-web3#2]
## Description

Alternative from using syntax below repetitively in many vue files.

```js
import abi from '../assets/abi.js'
// data state :
{
contractAddress: '0x0000000000000000000000',
}
// usage :
new window.web3.eth.Contract(abi, this.contractAddress)
```

## Tasks

- [ ] add setContractAddress API.
- [ ] add setAbi API.

**Comment by fauzan121002** [comment]
multi-arguments version: #3 

why have a single-argument function?

increased readability and flexibility for some cases using branching logic.

**Comment by fncolon** [comment]
After studying further, this action is an overkill, so I'm closing it for the time being.
